server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: ${DATABASE_DRIVER} #ex) com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL} #ex) jdbc:mysql://localhost:3306/pangarm
    username: ${DATABASE_USER} #ex) root
    password: ${DATABASE_PASSWORD} #ex) 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  jwt:
    secret: ${SPRING_JWT_SECRET} #ex) hrqwuiehfuhsdajhfuihwefijawhiufhwaefkjhweauhdfkjahduhf1398y4
    accessExpTime: ${SPRING_JWT_ACCESS-EXPTIME} # ex)100000000
    refreshExpTime: ${SPRING_JWT_REFRESH-EXPTIME} # ex)100000000

  data:

    elasticsearch:
      host: ${ELASTIC_SEARCH_HOST} # ex)localhost
      port: ${ELASTIC_SEARCH_PORT} # ex)9200

  precedent-client:
    url: ${PRECEDENT_CLIENT_URL} # ex)https://precedent-cherrypick.wookoo.shop

logging:
  level:
    root: INFO
